<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5PR7OFC" name="Command line test" tests="1" failures="1" timestamp="28 Apr 2019 10:42:34 GMT" time="0.096" errors="0">
  <testcase name="testAdd" time="0.011" classname="demodebug.demodebug.DemoMathTest">
    <failure type="java.lang.AssertionError" message="expected [15] but found [16]">
      <![CDATA[java.lang.AssertionError: expected [15] but found [16]
	at demodebug.demodebug.DemoMathTest.testAdd(DemoMathTest.java:24)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testAdd -->
</testsuite> <!-- Command line test -->
